config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 } 
  validates_uniqueness_of :list_id, :scope => :movie_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, only: [:new, :create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to root_path
  end

  private
  def find_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_add_bookmark.html.erb
<%= simple_form_for([list, bookmark], html: { class: "form-body"}) do |form| %>
  <%= form.label :comment %>
  <%= form.text_field :comment, class: 'form-control radius-12 mb-2' %>
  <%= form.association :movie, collection: Movie.all, class: 'form-control radius-12' %>
  <%= form.submit class: 'btn btn-gradient' %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1625&q=80);">
  <div class="container">
    <%= image_tag "logo.png", height: "100" %>
    <h1 id="show-h1" class="mb-5"><%= @list.name %></h1>
    <%= link_to "Back to Home", root_path, class: "btn btn-gradient" %>
  </div>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 radius-12 bg-white shadow mt-5">
      <%= render 'add_bookmark', list: @list, bookmark: @bookmark %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list, html: { class: "form-body"}) do |form| %>
    <%= form.label :name, class: 'w-100' %>
    <div class="form-control-container">
      <%= form.text_field :name, class: 'form-control w-70 radius-12' %>
      <%= form.submit class: 'btn btn-gradient w-20'%>
    </div>
<% end %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1625&q=80);">
  <div class="container">
    <%= image_tag "logo.png", height: "100" %>
    <h1 id="index-h1">Le Wagon's Movie DB</h1>
    <p>Because Teachers and Students are real Movies Fans and enjoy watching a good one.</p>
    <%= link_to "Create a new List", new_list_path, class: "btn btn-gradient" %>
  </div>
</div>
<div class="container mt-5">
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="list-item">
        <p><%= link_to list.name, list_path(list.id) %> <span class="small">(<%= list.bookmarks.size %>)</span></p>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1625&q=80);">
  <div class="container">
    <%= image_tag "logo.png", height: "100" %>
    <h1 id="new-h1">Le Wagon's Movie DB</h1>
    <p>Because Teachers and Students are real Movies Fans and enjoy watching a good one.</p>
    <%= link_to "Create a new List", new_list_path, class: "btn btn-gradient" %>
    <%= link_to "Back to Home", root_path, class: "btn btn-gradient" %>
  </div>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 radius-12 bg-white shadow mt-5">
      <%= render 'form', list: @list %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1625&q=80);">
  <div class="container">
    <%= image_tag "logo.png", height: "100" %>
    <h1 id="show-h1" class="mb-5"><%= @list.name %></h1>
    <%= link_to "Add a movie", new_list_bookmark_path(@list.id), class: "btn btn-gradient" %>
    <%= link_to "Back to Home", root_path, class: "btn btn-gradient" %>
  </div>
</div>
<div class="container mt-5">
  <div class="cards">
    <% @list.movies.each do |movie| %>
      <div class="card-product">
        <% bookmark = movie.bookmarks.find { |bookmark| bookmark.movie_id == movie.id && bookmark.list_id == @list.id } %>
        <%= link_to 'delete', bookmark_path(bookmark.id), method: :delete %>
        <img src="<%= movie.poster_url %>" />
        <div class="card-product-infos">
          <h2><%= movie.title %></h2>
          <p><%= movie.overview %></p>
          <p class="comment"><%= bookmark.comment %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>